### ISSUE TITLE
Types broke in 13.0.0

### ISSUE THREAD

**Issue by dd-jonas** [i18next/react-i18next#1654]
## 🐛 Bug Report

I'm using `i18next` version 23.2.8 which has the refactored types and it works without issues. But upgrading `react-i18next` to 13.0 breaks the typing of the `t` function.

## To Reproduce

[StackBlitz reproduction](https://stackblitz.com/edit/stackblitz-starters-wt6epn?file=src%2FApp.tsx)

```js
const { t } = useTranslation();

t('myKey').toLowerCase(); // Error: Property toLowerCase does not exist on type never,
```

## Expected behavior

Types should work like they used to.

```js
const { t } = useTranslation();

t('myKey').toLowerCase(); // Should work
```

## Your Environment

- *runtime version*: -
- *i18next version*: i.e. 23.2.8
- *os*: -

**Comment by adrai** [comment]
make sure your tsconfig has strict = true => https://stackblitz.com/edit/stackblitz-starters-zjbzmg?file=src%2FApp.tsx,src%2Fi18next.d.ts,src%2Ftranslations.ts,src%2Findex.tsx,package.json,tsconfig.json

**Comment by dd-jonas** [comment]
@adrai Thanks, that seems to improve it for the reproduction, but in my codebase I'm already using strict mode.

I think it might be related to the namespaces. I'm not providing defaultNS when initialising i18next, and don't provide a defaultNS in the TypeScript declaration file. I always call `useTranslation()` without any namespaces, and provide it in the `t` function (e.g. `t('common:my.key')` or `t('auth:other.key')`). Does this approach not work anymore?

**Comment by adrai** [comment]
it is suggested to pass the namespace via t options => `t('my.key', { ns: 'common' })`

**Comment by schneideramanda** [comment]
The same error happens here when using template literals after upgrading from v12 to v13. I'm also using strict mode and never provided the namespace as param for the translations.

![Screenshot at Jul 14 17-04-49](https://github.com/i18next/react-i18next/assets/76711874/f483659a-b4a8-45f6-9153-69fb795611c2)

**Comment by adrai** [comment]
@schneideramanda please provide a reproducible example... not just code snippets or screenshots

**Comment by dd-jonas** [comment]
> it is suggested to pass the namespace via t options => `t('my.key', { ns: 'common' })`

That would be really cumbersome to add a couple thousand times while it used to work without it.

**Comment by dd-jonas** [comment]
Still not working with `i18next@23.3.0` and `react-i18next@13.0.2`

**Comment by pedrodurek** [comment]
Hey @dd-jonas. If you want it to work with this syntax: `t('common:my.key')`, `t('auth:other.key')`, you must pass the namespaces to the `useTranslation` hooks, that's a requirement. For example:
```tsx
const {t} = useTranslation(['common', 'auth']);

t('common:my.key');
t('auth:other.key')
```

**Comment by dd-jonas** [comment]
Thanks for your answer @pedrodurek. If that's the correct approach, I'll pass the namespaces like you mentioned.

I want to note though that, even though types don't work correctly without passing namespaces (e.g. `t` is typed as `(key: string) => never`), the types still work once I fully write a valid key in `"namespace:key"` format. For example:

```ts
const { t } = useTranslation();

// const t: TFunction<unknown, TOptions<$Dictionary<any>>, never>(...args: [key: unknown, options?: (TOptionsBase & $Dictionary<any> & InterpolationMap<never>) | undefined] | [key: ...] | [key: ...]) => never
// Error: Type '[]' is not assignable to type '[key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary<any> & InterpolationMap<never>) | undefined]'. Source has 0 element(s) but target requires 2.
t();

// const t: TFunction<"invalid", TOptions<$Dictionary<any>>, never>(...args: [key: "invalid" | "invalid"[], options?: (TOptionsBase & $Dictionary<any> & InterpolationMap<never>) | undefined] | [key: ...] | [key: ...]) => never
// No error, but return type is never
t('invalidKey');
t('invalidNs:invalidKey');
t('validKeyWithoutNs');

// const t: TFunction<"validNs:validKey", TOptions<$Dictionary<any>>, string>(...args: [key: "validNs:validKey" | "validNs:validKey"[], options?: (TOptionsBase & $Dictionary<any> & InterpolationMap<...>) | undefined] | [key: ...] | [key: ...]) => string
// Works fine, hence my confusion
t('validNs:validKey');
```

---

If there is no follow up needed, this issue may be closed for me. Cheers!

**Comment by pedrodurek** [comment]
Hey @dd-jonas, for invalid keys, you should pass a default value to infer the proper return type. For example:
```tsx
t('invalidKey', 'default value');
// or
t('invalidKey', {defaultValue: 'default value'});
```

**Comment by Thomas-CT** [comment]
`returnObjects` is also broken after updating to v13, when using arrays:
```js
{t('array', {
  returnObjects: true,
}).map((element) => element)} // Property 'map' does not exist on type '$SpecialObject'.
```

**Comment by adrai** [comment]
tests are working as expected: https://github.com/i18next/i18next/blob/907caeaf821976ffde47d2ff30ef1464045c2b6d/test/typescript/t.test.ts#L130

**Comment by Thomas-CT** [comment]
It's only a type issue. I get no runtime errors. 
It works fine if I cast it, but that shouldn't be necessary:

```js
t('array', {
  returnObjects: true,
}) as string[]).map((element) => element) // No errors
```

**Comment by adrai** [comment]
Feel free to open a PR.
// cc: @pedrodurek

**Comment by pedrodurek** [comment]
When setting `returnObject` as true, the value inferred will be `object | Array<string | object>`, that means it can be either an object or array. In order to call array's specific methods without asserting the value, you need to narrow it down like in [this example](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwwAoBKALnhwCMArcDeAH3gEEYYoBPAHgGcMYsqAOaMKNOgD4A3ACgZYPH3hweyCPQC8BErKyJ4hFWvqC+UdCBz7W7DsXgBvGfGUhV6gHQBbKAAdCJPAaEq7uGMSyAL5AA). We can only infer the exact return type of the `t` function if you define the `resources` type and if your translations are placed in ts files rather than json files, like in [this example](https://codesandbox.io/p/sandbox/i18n-basic-example-y2yjpw?file=/src/App.tsx:7,11).

**Comment by Thomas-CT** [comment]
That makes sense. I was missing i18next.d.ts.ts, after the upgrade. It's working now with translations in both .json and .ts.

**Comment by Chopper94** [comment]
Hi, I have kinda similar issue here - https://stackblitz.com/edit/stackblitz-starters-gxozwf?file=src%2FApp.tsx,src%2Fi18next.d.ts,src%2Ftranslations.ts,src%2Findex.tsx,package.json,src%2Fstyle.css 
After trying to reproduce the issue I understood that it has to do with translation keys  e.g. `global.foo`. 
Even though I have `keySeparator: false` , both variables with and without specified NS are resolved as `never`. However my expectation was that setting  `keySeparator: false` will allow types resolve with correct value.

Is it expected behaviour? Any suggestions for my case?
Thanks!
