### ISSUE TITLE
Type error with typescript 4.6

### ISSUE THREAD

**Issue by jansepke** [i18next/react-i18next#1459]
## 🐛 Bug Report

After upgrading typescript from 4.5.5 to 4.6.2 we get the following error when running tsc:

```
node_modules/react-i18next/ts4.1/index.d.ts:333:14 - error TS2344: Type 'ComponentProps<C>' does not satisfy the constraint 'WithTranslationProps'.
  Type 'unknown' is not assignable to type 'WithTranslationProps'.

333     Subtract<React.ComponentProps<C>, WithTranslationProps>
                 ~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/react-i18next/ts4.1/index.d.ts:333
```

## Expected behavior

react-i18next should also be valid typescript for typescript 4.6

## Your Environment

- *runtime version*: node v14.19.0
- *i18next version*: 21.6.0
- *os*: Linux

**Comment by cojoclaudiu** [comment]
I confirm the same error Vite React Typescript

```
> tsc && vite build

node_modules/react-i18next/ts4.1/index.d.ts:333:14 - error TS2344: Type 'ComponentProps<C>' does not satisfy the constraint 'WithTranslationProps'.
  Type 'unknown' is not assignable to type 'WithTranslationProps'.

333     Subtract<React.ComponentProps<C>, WithTranslationProps>
                 ~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/react-i18next/ts4.1/index.d.ts:333
```

**Comment by Anubiso** [comment]
Having the same issue

**Comment by wizzymotion** [comment]
same issue here using VITE too

**Comment by ortegarenzy** [comment]
Same issue:

Vite 2.8.0
TypeScript 4.5.5
ViteJS Plugin React 1.0.7

```
node_modules/react-i18next/ts4.1/index.d.ts:333:14 - error TS2344: Type 'ComponentProps<C>' does not satisfy the constraint 'WithTranslationProps'.
  Type 'unknown' is not assignable to type 'WithTranslationProps'.

333     Subtract<React.ComponentProps<C>, WithTranslationProps>
                 ~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/react-i18next/ts4.1/index.d.ts:333

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by cojoclaudiu** [comment]
> TypeScript 4.5.5
Are you sure is TypeScript 4.5.5 and not 4.6.2?

I'm asking because I had the same issue with @4.6.2 but I rollback to @4.5.5 and it's fine.

**Comment by adrai** [comment]
should be fixed with v11.15.6

**Comment by cojoclaudiu** [comment]
I confirm now the build it's working with the @11.15.6 update. (Vite, React, Typescript)
