### ISSUE TITLE
I18nextProvider and testing recipe doesn't work with i18next v21.0.1 (typecheck error)

### ISSUE THREAD

**Issue by belgattitude** [i18next/react-i18next#1379]
## 🐛 Bug Report

After upgrade of i18next from 20.6.1 to v21.0.1 the code related to [react-i18next / testing without stubbing](https://react.i18next.com/misc/testing#testing-without-stubbing) complains about a missing `reportNamespaces` prop when instanciating the react-i18next provider.

Error output:

```
error TS2741: Property 'reportNamespaces' is missing in type 'import("/home/sebastien/github/nextjs-monorepo-example/node_modules/i18next/index").i18n' but required in type 'import("/home/sebastien/github/nextjs-monorepo-example/node_modules/next-i18next/node_modules/i18next/index").i18n'.
```

## To Reproduce

You can reproduce it on this branch:  https://github.com/belgattitude/nextjs-monorepo-example/pull/458 or see the error message on the CI here: https://github.com/belgattitude/nextjs-monorepo-example/pull/458/checks?check_run_id=3672972037

Example code (was working on i18next < 21):

```typescript
import i18n from 'i18next';
import type { FC } from 'react';
import { initReactI18next, I18nextProvider } from 'react-i18next';

/**
 * Fully wrapped strategy for i18next, you can use stub/mocks as well
 * @link {https://react.i18next.com/misc/testing}
 */
i18n.use(initReactI18next).init({
  lng: 'en',
  fallbackLng: 'en',
  ns: ['common'],
  defaultNS: 'common',
  debug: false,
  interpolation: {
    escapeValue: false, // not needed for react!!
  },
  // Let empty so you can test on translation keys rather than translated strings
  resources: { en: { common: {} } },
});

export const I18nextTestStubProvider: FC = ({ children }) => {
  // THIS BREAKS AND COMPLAIN ABOUT MISSING reportNamespaces Prop.
  return <I18nextProvider i18n={i18n}>{children}</I18nextProvider>;
};
```

## Expected behavior

Should not break.

## Your Environment

- *runtime version*: node 14 lts
- *i18next version*:  21.0.1
- *react-i18next version*: i.e. 21.0.1
- *os*: Ubuntu
- *typescript*: 4.4.3

**Comment by adrai** [comment]
Strange there was no TypeScript change in that area.... maybe @pedrodurek knows more?

**Comment by pedrodurek** [comment]
it seems the augmentation is not working for the `config/jest` path, I'll investigate the reason:
https://github.com/i18next/react-i18next/blob/master/ts4.1/index.d.ts#L83-L92

**Comment by belgattitude** [comment]
@pedrodurek

> It seems the augmentation is not working for the `config/jest` path

Tested from other folders and it seems to be unrelated to the path.

But thanks to your link, I've added the augmentation in the react-i18next.d.ts declaration file (following https://react.i18next.com/latest/typescript).

```typescript
import 'react-i18next';
import type { ReportNamespaces } from 'react-i18next';
import common from '../../public/locales/en/common.json';

// For an obscure reason i18n type augmentation present in react-i18next/ts4.1/index.d.ts
// (and/or react-i18next/index.d.ts) aren't considered when using I18nextProvider
// @see https://github.com/i18next/react-i18next/issues/1379
declare module 'i18next' {
  interface i18n {
    reportNamespaces: ReportNamespaces;
  }
}

declare module 'react-i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common';
    resources: {
      common: typeof common;
      //....
    };
  }
}
```

That might actually make sense.

**Comment by pedrodurek** [comment]
I wanna keep this issue opened for now for further investigation, the workaround implemented shouldn't be needed.
