### ISSUE TITLE
Trans component using context has unexpected type errors

### ISSUE THREAD

**Issue by aligg** [i18next/react-i18next#1749]
## 🐛 Bug Report
- I'm working on upgrading from version 13.3.0 to 14.1.0. After upgrading I have a Trans component that uses the context prop that gets a type error. It is the only place we use context in the codebase. 

The error appears as follows below (note how in the strings get a letter dropped): 
```
src/components/features/CertifyWeeklyIconListItem/CertifyWeeklyIconListItem.tsx:77:13 - error TS2820: Type '"about_certifying"' is not assignable to type '"aboutertifying" | "aboutertifying_pending" | "beginertifying" | "beginertifying_date" | "certifyeading_filed" | "certifyow_button" | (string & ("aboutertifying" | "aboutertifying_pending" | "beginertifying" | "beginertifying_date" | "certifyeading_filed" | "certifyow_button")[])'. Did you mean '"aboutertifying"'?

77             i18nKey="about_certifying"
               ~~~~~~~

  src/components/features/CertifyWeeklyIconListItem/CertifyWeeklyIconListItem.tsx:77:13
    77             i18nKey="about_certifying"
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from property 'i18nKey' which is declared here on type 'IntrinsicAttributes & { t: TFunction<"featureComponents", "certify_section">; i18nKey: string; context: string; components: { howToCertifyLink: Element; howToRemainEligibleLink: Element; certifyLink: Element; }; } & { ...; }'
```

As a workaround, we are removing the use of context after which the type checks pass. 

## To Reproduce
Our code uses the Trans component with context and began seeing the above error after version 14.0.0. 

Our code: 

```js
import { Trans, useTranslation } from 'react-i18next'

.. 


  )}
          <Trans
            t={t}
            i18nKey="about_certifying"
            context={claimantState}
            components={{
              howToCertifyLink: (
                <a
                  href={Routes.HOW_TO_CERTIFY}
                  target="_blank"
                  rel="noopener noreferrer"
                />
              ),
         .... more links passed in
                />
              ),
            }}
          />
```

```
Translation file keys look like: 


"featureComponents": {
    "certify_section": {
      "about_certifying": "<strong>If you don't <howToCertifyLink>certify each week</howToCertifyLink>, or if you <howToRemainEligibleLink>become ineligible</howToRemainEligibleLink> for unemployment, your payments will be paused</strong> and your application will need to be reviewed. We may ask you to provide more information.",
      "about_certifying_pending": "You'll need to <howToCertifyLink>answer some questions and remain eligible in order to receive your payments</howToCertifyLink> for each week. The first time you certify, make sure to certify for every week since you submitted your application.",
      "begin_certifying": "Begin certifying to get paid",
      "begin_certifying_date": "Begin certifying on {{date, long_date}} to get paid",
      "certify_heading_filed": "Certify your unemployment every week",
      "certify_now_button": "Certify now"
    },
```

## Expected behavior
I would expect the type checks to pass 

## Your Environment

- *runtime version*: "node": ">=20.11.1"
- *i18next version*: any 14.0.0 and above
- *os*: Mac

**Comment by adrai** [comment]
Same as here: https://github.com/i18next/i18next/issues/2177#issuecomment-2071564836
Set the contextSeparator and the pluralSeparator option to a different character.

**Comment by marcalexiei** [comment]
I'm not able to reproduce the issue with a minimal example where I use default values for the two separators. 

> [!TIP]
changing `contextSeparator` or `pluralSeparator` to another character, since you are already using `_` inside keys, might be more a explicit way to highlight when a key has a context or a plural variant.

<details>
  <summary>Component code</summary>

```tsx
import * as React from 'react';
import { Trans, useTranslation } from 'react-i18next';

function Test(): React.JSX.Element {
  const { t } = useTranslation(['context']);

  const context = 'cake' as 'pending' | 'active';

  return (
    <Trans
      t={t}
      i18nKey="certify_section.about_certifying"
      context={context}
      components={{ howToCertifyLink: <a /> }}
    />
  )
}
```
</details>

<details>
  <summary>i18n.d.ts</summary>


```tsx
import 'i18next';

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'custom';
    allowObjectInHTMLChildren: true;
    resources: {
      context: {
        certify_section: {
          about_certifying: "<strong>If you don't <howToCertifyLink>certify each week</howToCertifyLink>";
          about_certifying_pending: "You'll need to <howToCertifyLink>answer some questions and remain eligible in order to receive your payments</howToCertifyLink> for each week. The first time you certify.";
        };
      };
    };
  }
}

```
</details>


<img width="1283" alt="image" src="https://github.com/i18next/react-i18next/assets/24919330/48d640c5-e980-4b50-ab89-d2874f1c1607">

----

This scenario is already tested in `TransWithoutContext.test.tsx`
https://github.com/i18next/react-i18next/blob/70176d9080d72c95cf569b276f4cb3d1b2498768/test/typescript/custom-types/TransWithoutContext.test.tsx#L122

----

> [!NOTE]
> Be sure to have configured i18next types properly. 
> If you still experience the error, reopen the issue providing a complete minimal reproduction example (not just code snippets).
