### ISSUE TITLE
Doesn't work with Babel 5.8.3 and React 1.4.5

### ISSUE THREAD

**Issue by tarkanlar** [i18next/react-i18next#8]
I get this error in console and Uncaught Error: Cannot find module 'react' 
webpack also throw error 
WARNING in ./~/react-i18next/bin/index.js
Critical dependencies:
1:414-421 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to
get better results.
 @ ./~/react-i18next/bin/index.js 1:414-421

**Comment by jamuhl** [comment]
use `require('react-i18next/lib')` to require non-prebuild version.

**Comment by tarkanlar** [comment]
Hey thanks a lot, it worked but now i get error 
"missingKey tr-TR common appName appName" although i have a folder named 'tr-TR' and common.json and appName inside it same as in example folder.

**Comment by jamuhl** [comment]
do you only get this warning...or does the UI work as expected (gets the appName in tr-TR)?

the point is the translated hoc only triggers a load of resources and a rerender via props change on its children when resources get available...but does not prevent rendering until loaded...so first render loop will be done before loaded resources and props.t will result in missing key.

might add an option to translated hoc, preventing component rendering until loading is done...what do you think?

**Comment by tarkanlar** [comment]
Hey @jamuhl thanks for reply,
UI doesn't get the translation instead just shows the 'appName' as text. 
Btw i am using this with redux maybe something breaking the code when i am connecting i do
```js export default connect(null, bindActions)(translate('common')(Header)); ```
which may be the reason of the bug

**Comment by jamuhl** [comment]
can you set debug=true in i18next.init? seems the translation.json got not loaded

**Comment by tarkanlar** [comment]
Yep. json seems to be loaded 

```
i18next::translator: missingKey tr-TR common explore explore
logger.js?0e55:29 i18next: languageChanged tr-TR
logger.js?0e55:29 i18next: initialized Object {debug: true, ns: Array[1], defaultNS: "common", fallbackLng: Array[1], fallbackNS: false…}
2logger.js?0e55:29 i18next::translator: missingKey tr-TR common explore explore
```

**Comment by jamuhl** [comment]
no there should be some logs `loaded namespace` - can you access the common.json?!?

**Comment by tarkanlar** [comment]
Oh! no i can't
```
i18next::backendConnector: loading namespace common for language tr-TR failed failed parsing /locales/tr-TR/common.json to json
logger.js?0e55:29 i18next::backendConnector: loading namespace common for language tr failed failed parsing /locales/tr/common.json to json
logger.js?0e55:29 i18next::backendConnector: loading namespace common for language en failed failed parsing /locales/en/common.json to json
```

**Comment by tarkanlar** [comment]
Yep, fixed it by adding "" to object
explore: "Explore" to "explore":"Explore"

Thanks.

But i think we should fix the example with both changing common.json file and changing require to  require('react-i18next/lib')

**Comment by jamuhl** [comment]
glad you found it. added an info to readme.
