### ISSUE TITLE
tsc not working with last release 11.16.8 - compilation error on HTMLAttributes

### ISSUE THREAD

**Issue by emish89** [i18next/react-i18next#1498]
## 🐛 Bug Report

After upgrading from `11.16.7` to `.8` I get an error with `tsc `command. 
```
node_modules/@types/react/index.d.ts:1830:15 - error TS2428: All declarations of 'HTMLAttributes' must have identical type parameters.

1830     interface HTMLAttributes<T> extends AriaAttributes, DOMAttributes<T> {
                   ~~~~~~~~~~~~~~

node_modules/react-i18next/ts4.1/index.d.ts:106:13 - error TS2428: All declarations of 'HTMLAttributes' must have identical type parameters.

106   interface HTMLAttributes {
                ~~~~~~~~~~~~~~
```
## To Reproduce

Update to last version in a CRA app with `react 18.1.0` and run `tsc `for typescript compilation

## Expected behavior

it works as the 11.16.7

## Your Environment

- react 18.1.0
- CRA
- 11.16.8 version of this lib
- node LTS

**Comment by shensven** [comment]
+1
see here https://github.com/shensven/Yadds/runs/6301358617?check_suite_focus=true

**Comment by niklaskallander** [comment]
+1, I'm also experiencing this issue when upgrading to v11.16.8

**Comment by doron-cohen** [comment]
Same here. Seems to be caused by 8ed568a3faed01d33a1196fd1d26fceffc92ac63

**Comment by pedrodurek** [comment]
I opened a PR to fix it, but I usually recommend people to set `skipLibCheck` to `true` to avoid inconsistent types among libraries.

**Comment by adrai** [comment]
should be fixed with v11.16.9
