### ISSUE TITLE
Type error when used with typescript 4.5.2

### ISSUE THREAD

**Issue by jansepke** [i18next/react-i18next#1407]
## 🐛 Bug Report

After upgrading typescript to 4.5.2 (from 4.4.4), a build with react-i18next (11.14.2) fails with this error message:

```
node_modules/react-i18next/ts4.1/index.d.ts:259:35 - error TS2344: Type 'undefined' does not satisfy the constraint 'KeyPrefix<N>'.
TKPrefix extends KeyPrefix<N> = undefined,

node_modules/react-i18next/ts4.1/index.d.ts:283:35 - error TS2344: Type 'undefined' does not satisfy the constraint 'KeyPrefix<N>'.
TKPrefix extends KeyPrefix<N> = undefined
```

## To Reproduce

Install react-i18next 11.14.2 and typescript 4.5.2 and run `tsc`.

## Expected behavior

No failed build.

## Your Environment

- *runtime version*: node v14.18.1
- *i18next version*: 21.5.2
- *os*: Linux

**Comment by guguji5** [comment]
I have the same issue on mac, typescript: 4.3.2, react-i18next: 11.11.1

**Comment by pedrodurek** [comment]
Hey @guguji5 and @jansepke, is the flag `skipLibCheck` set to `true` in your tsconfig?

**Comment by grxy** [comment]
I also ran into this issue, and it looks to be caused by [this breaking change](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#restrictions-on-assignability-to-conditional-types).
