### ISSUE TITLE
This JSX tag's 'children' prop expects a single child of type 'ReactI18NextChild | Iterable<ReactI18NextChild>' when using `allowObjectInHTMLChildren`

### ISSUE THREAD

**Issue by davehowson** [i18next/react-i18next#1543]
## 🐛 Bug Report

After upgrading to React v18 and Reacti18Next to v11.18, I had an issue with objects not being accepted inside the `Trans` component, something similar to [this](https://github.com/i18next/react-i18next/issues/1504).
The fix for that was to add the `allowObjectInHTMLChildren` property, which fix that issue, but it lead to another issue.
Now, when I try to have the result of a `t` function along with some other strings inside a `p` or `span` component, I get the error

```
This JSX tag's 'children' prop expects a single child of type 'ReactI18NextChild | Iterable<ReactI18NextChild>' when using `allowObjectInHTMLChildren
````

## To Reproduce

Codesandbox - https://codesandbox.io/s/react-i18next-type-issue-uidhq7
Please check the error on `src/App.tsx:10`

```js
<p>{t("simpleContent")} with extra stuff</p>
```

## Proposed Solution

I tried playing around with the types in the library and it seems like changing `node_modules/react-i18next/ts4.1/index.d.ts:108` as follows will fix this.

```
declare module 'react' {
  interface HTMLAttributes<T> {
    children?: ReactI18NextChild | ReactI18NextChild[];
  }
}
```

The problem, at least for me, seems to be with `Iterable<ReactI18NextChild>` not working as expected for multiple children

**Comment by dave-multiplier** [comment]
Hi @pedrodurek, any update on this?
I was planning on using https://github.com/ds300/patch-package to solve this for now, unless a PR is in the works?

**Comment by eiskalteschatten** [comment]
We're also having this problem unfortunately. ☹️

**Comment by debugelton** [comment]
same problem also with React 17 and react-i18next (v11.18.3)

**Comment by JCMais** [comment]
This is probably because the type definition is `React.ReactNode | Record<string, unknown>`, while i18next type definition has `object` in the union type: https://github.com/i18next/i18next/blob/132a02461479c1b14709ff0bce1db484578ccb30/index.d.ts#L687


I think (could be wrong) that `Record<string, unknown>` and object are not compatible if you change i18next to `React.ReactNode | object` it works.

I also changed from `Iterable<ReactI18NextChild>` to `ReactI18NextChild[]`

**Comment by benjamincotrel** [comment]
I'm having a similar problem with PropTypes.InferProps. If I use PropTypes.node for my children prop, and use {children} in a simple div, I get this error:

Type 'ReactNodeLike' is not assignable to type 'ReactI18NextChild | Iterable<ReactI18NextChild>'.
  Type '{}' is not assignable to type 'ReactI18NextChild | Iterable<ReactI18NextChild>'.

**Comment by sshmyg** [comment]
Just never do this in open source libs.
If you want to custom children, just use custom types. Never reassign types of different lib!

![image](https://user-images.githubusercontent.com/1410608/191231326-61611975-90c4-434a-b8d0-ef1cee6f74f1.png)

**Comment by kanonieer** [comment]
Same problem after bumping React to v18

**Comment by mswezey23** [comment]
I'm having this issue when using the following tech stack:

TS, Chakra, React 18, react i18 next:

This works:
```
   <NavLink to={path}>
      {({ isActive }: { isActive: boolean }) => (
        <Flex
          align='center'
          p='4'
          mx='4'
          role='group'
          borderRadius='99px'
          _hover={{
            bg: 'purple.50',
            color: '#000080',
          }}
          bg={isActive ? 'purple.50' : undefined}
          color={isActive ? '#000080' : undefined}
          {...rest}
        >
          {icon && <Image src={icon} boxSize='25px' mr='4' />}
          <Text fontSize='16px' fontWeight={400}>
            {children}
          </Text>
        </Flex>
      )}
    </NavLink>
```

I expected this to work, but it errors out in the IDE:

Error: `Type '({ isActive }: { isActive: boolean; }) => JSX.Element' is not assignable to type 'ReactI18NextChild | Iterable<ReactI18NextChild>'.ts(2322)`

```
  <Link
      as={NavLink}
      to={path}
      style={{ textDecoration: 'none' }}
      cursor='pointer'
      color={'gray.600'}
      _active={{
        bg: 'purple.50',
        color: '#000080',
        borderRadius: '99px',
      }}
      _activeLink={{
        bg: 'purple.50',
        color: '#000080',
        borderRadius: '99px',
      }}
    >
      {({ isActive }: { isActive: boolean }) => (
        <Flex
          align='center'
          p='4'
          mx='4'
          role='group'
          borderRadius='99px'
          _hover={{
            bg: 'purple.50',
            color: '#000080',
          }}
          bg={isActive ? 'purple.50' : undefined}
          color={isActive ? '#000080' : undefined}
          {...rest}
        >
          {icon && <Image src={icon} boxSize='25px' mr='4' />}
          <Text fontSize='16px' fontWeight={400}>
            {children}
          </Text>
        </Flex>
      )}
  </Link>
```

**Comment by rjaguilar** [comment]
Same

**Comment by davidpp** [comment]
Same issue here

**Comment by estrelasteinkirch** [comment]
same here

**Comment by cuttleman** [comment]
same issue here

**Comment by rene-stesl** [comment]
same issue if you have something like `<span>{props.somePassedInReactNodeOrReactElement}</span>`

**Comment by renomateo** [comment]
Same issue here

**Comment by sklawren** [comment]
Same issue

**Comment by sergiohgz** [comment]
This is a big issue relative to typingm due to redefining children of react module.
This is not a good practise, as it breaks other typings.

```typescript
This JSX tag's 'children' prop expects a single child of type 'ReactI18NextChild | Iterable<ReactI18NextChild>', but multiple children were provided.
but multiple children were provided.
```

**Comment by rene-stesl** [comment]
Is that really the solution to just ignore the growing number of Typescript Users?
Why has this type been overridden in the first place? Just leave react typings alone, please!
Does it really need that override? What is it for?

**Comment by jamuhl** [comment]
@rene-stesl idk...but this module is far from ignoring typescript users. Just go through the changelog https://github.com/i18next/react-i18next/blob/master/CHANGELOG.md and check how many releases are just related to work for typescript users.

@pedrodurek puts a lot of his own (free) time into improving the typings and does an awesome job for the community.

**Comment by pedrodurek** [comment]
Thanks for backing me up @jamuhl, I appreciate it!

@rene-stesl, the types here work perfectly, sometimes it's just hard to please everyone, but I'm doing my best here to address the issues whenever I have free time. 
When it comes to complex types like the i18next ones, where we recursively go through all translations to infer the appropriate `keys` and `return` type, we need to be careful to address some issues due to compilation time concern, so there is a lot of effort on testing and benchmarking it.

**Comment by rene-stesl** [comment]
@jamuhl, @pedrodurek I know that it is not easy to sacrifice your free time for such a project and only get criticism. This is definitely not my intention.

But IMHO this ticket gets ignored since it was opened on Aug 15. I personally don't think the Types work perfectly in this case because if you just add react-i18next as dependency to an existing project it is possible that the build fails! And I personally think that just adding a dependency to a project shouldn't be able to do that!

If someone can explain why the React Types were overwritten, it might be easier to find a solution.

**Comment by jamuhl** [comment]
@rene-stesl 

I guess (not a typescript user):

- react team decided to make types stricter not allowing objects inside the react-element children array (as it makes no sense to their use case -> you can't render objects)

in react-i18next we decided long before that objects are a good way to pass in interpolation values and keeping i18next translation syntax `<Trans>Some interpolation by passing in an object {{theObject}}</Trans>`. That is absolute valid in javascript.

So the solution is either to extend the types or not using objects inside react-elements.

(Like said - i don't use typescript - so I'm just believe that this was the reason)

**Comment by stee-ren** [comment]
@pedrodurek I'd love to hear your thoughts on this problem since you are clearly a Typescript user. I think most people on this thread use typescript and I would hope that if the real crux of the problem was clarified, then maybe someone might find an elegant solution that makes your life easy.

**Comment by rene-stesl** [comment]
Ok so I just quickly went over the the said typings. I would love to take a deeper look but I have absolutely no time for this.

As far as I can see the react typing for the DOMAttributes look like this (and it seems like this was even the case with react 16, so no changes there)
```
interface DOMAttributes<T> {
    children?: ReactNode | undefined;
    ...
```

The override of react-i18next
```
type ObjectOrNever = TypeOptions['allowObjectInHTMLChildren'] extends true
  ? Record<string, unknown>
  : never;
type ReactI18NextChild = React.ReactNode | ObjectOrNever;

declare module 'react' {
  interface HTMLAttributes<T> {
    children?: ReactI18NextChild | Iterable<ReactI18NextChild>;
  }
}
```

I'm absolutely **no** Typescript expert but the proposed solution by @davehowson is working and would be my suggested quick fix as well. I guess that the problem lies in the use of the Iterable interface, since any Object could be iterable if it implements the interface. So my best bet is that the Typescript interpreter just want's to tell us that our provided Object doesn't implement the Iterable interface and therefore throws this error. With the use of ReactI18NextChild[] however, we tell Typescript that it has to be an Array. So Typescript knows that the Object applies to ReactI18NextChild instead of Iterable<ReactI18NextChild>.
But as said I'm really no expert, I'm just guessing 🤣😉😅.

The big question is since react 16 used the same typing for the children, why is this "hack" needed now?

**Comment by AkiraVoid** [comment]
Just a workaround: use fragment `<></>` to surround you children.

**Comment by wiinxt** [comment]
Hi, did you try to add `allowObjectInHTMLChildren: true` in `react-i18next.d.ts` ?
```js
import 'react-i18next'

declare module 'i18next' {
	interface CustomTypeOptions {
		returnNull: false
		allowObjectInHTMLChildren: true // add this solve my issue
	}
}
```
I have `react-i18next` v12, `typescript` v4.9 and `react` v18.2

I think https://github.com/i18next/i18next/issues/1859 is a duplicate of this issue

**Comment by DSamniashvili** [comment]
Same issue here!
type '{ lng: ReactNode; }' is not assignable to type 'ReactI18NextChild | Iterable<ReactI18NextChild>'.

Object literal may only specify known properties, and 'lng' does not exist in type 'ReactElement<any, string | JSXElementConstructor<any>> | ReactFragment | ReactPortal | Iterable<ReactI18NextChild>'.ts(2322)
index.d.ts(46, 5): 

The expected type comes from property 'children' which is declared here on type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'

**Comment by adrai** [comment]
out of curiosity... check with i18next v22.4.4

**Comment by rene-stesl** [comment]
Tried it with v22.4.6, same issue:

TS2322: Type 'ReactNode | ((data: DataNode) => ReactNode)' is not assignable to type 'ReactI18NextChild | Iterable<ReactI18NextChild>'.   Type '(data: DataNode) => ReactNode' is not assignable to type 'ReactI18NextChild | Iterable<ReactI18NextChild>'.

**Comment by rene-stesl** [comment]
Even tried to update react-i18next from 11.18.6 to 12.1.1, but then i get a big pile of typescript errors.
e.g:

- TS2746: This JSX tag's 'children' prop expects a single child of type 'ReactNode', but multiple children were provided
- TS2322: Type 'ReactI18NextChild | Iterable<ReactI18NextChild>' is not assignable to type 'ReactNode'.   Type 'Record<string, unknown>' is not assignable to type 'ReactNode'.     Type 'Record<string, unknown>' is missing the following properties from type 'ReactPortal': key, children, type, props

**Comment by ViktorQvarfordt** [comment]
Why does this package introduce this type override?
```ts
declare module 'react' {
  interface HTMLAttributes<T> {
    children?: ReactI18NextChild | Iterable<ReactI18NextChild>;
  }
}
```

Is this really necessary? It breaks other types in our project.

**Comment by idfunctor** [comment]
@pedrodurek react-18next completely breaks function as children in render props. A lot of projects are completely built on top of this library & it's really not possible to find alternatives. It would be nice if you at least let us know if we can submit a PR implementing @davehowson's solution, or if there is something else we could do. I would be happy to try to work on this but it is just not possible to keep React 18 and react-i18next both, without disabling typescript for multitudes of files.

**Comment by stee-ren** [comment]
Any update on this?

**Comment by fresonn** [comment]
Omg it breaks functionality, please fix it

**Comment by adrai** [comment]
v12.1.5 should address this... more infos here: #1606

**Comment by fresonn** [comment]
@adrai It works, thanks

**Comment by rene-stesl** [comment]
I've updated to "i18next": "22.4.9" and "react-i18next": "12.1.5".
Now I've some problems using MUI.

If I try to use MUIs Autocomplete with the PaperComponent prop, I get following error:
 ```
TS2322: Type 'ReactI18NextChildren' is not assignable to type 'ReactNode'.
Type 'Record<string, unknown>' is not assignable to type 'ReactNode'.
Type 'Record<string, unknown>' is missing the following properties from type 'ReactPortal': key, children, type, props
```

Using MUIs Card Component:
```
TS2746: This JSX tag's 'children' prop expects a single child of type 'ReactNode', but multiple children were provided.
```

Same with TextField:
```
The types of 'InputLabelProps.children' are incompatible between these types.
Type 'ReactI18NextChildren' is not assignable to type 'ReactNode'.
Type 'Record<string, unknown>' is not assignable to type 'ReactNode'.
Type 'Record<string, unknown>' is missing the following properties from type 'ReactPortal': key, children, type, props
```

Anyone else have these problems?

**Comment by ChrisZieba** [comment]
@rene-stesl I noticed this as well after updating to 12.1.5, but only in `Trans` usage:
```jsx
                  <Trans i18nKey="key">
                    There are
                    <i>{{ value: someValueVariable }} days</i> in
                    a month.
                  </Trans>
```
<img width="976" alt="Screenshot 2023-02-06 at 11 16 46" src="https://user-images.githubusercontent.com/2230570/217064238-4f4ae32e-33b3-4940-bd28-7334492e0316.png">

I guess in theory I could just split this out or wrap in a fragment, but I would have to do this in over 300 places 🤔

**Comment by gabrielbull** [comment]
This issue should not be closed, it is still present on latest version of everything. This library should not be overriding the react types, period. For those still struggling, adding this type worked for me:

```
declare module "i18next" {
  interface TypeOptions {
    returnNull: false;
    allowObjectInHTMLChildren: false;
  }
}
```

**Comment by Aigarsss** [comment]
Having the same problem

**Comment by Aigarsss** [comment]
Still having the same problem on 12.1.5 as well

**Comment by nahumzs** [comment]
Sorry to join the boat of complaining but this is really annoying. Why something like this should override React base types? Any react render function is currently broken :(. Is yet not an official answer?

**Comment by adrai** [comment]
> Sorry to join the boat of complaining but this is really annoying. Why something like this should override React base types? Any react render function is currently broken :(. Is yet not an official answer?

@pedrodurek maybe this also needs to be clarified?

**Comment by marklai1998** [comment]
Please reopen this, its kinda irresponsible

**Comment by adrai** [comment]
Please check if that can be reverted now: https://github.com/i18next/react-i18next/pull/1653

@davehowson @ghost @eiskalteschatten @debugelton @JCMais @neatroapp @sshmyg @kanonieer @rjaguilar @davidpp @estrelasteinkirch @cuttleman @rene-stesl @renomateo @sklawren @sergiohgz @stee-ren @AkiraVoid @wiinxt @DSamniashvili @ViktorQvarfordt @idfunctor @fresonn @ChrisZieba @gabrielbull @Aigarsss @BrunoQuaresma @nahumzs

**Comment by pedrodurek** [comment]
For reference, in case anyone disagrees with the approach used here: https://github.com/i18next/react-i18next/pull/1653#issuecomment-1631512452

**Comment by pedrodurek** [comment]
If anyone faces any problem/bug because of the approach used here, please create a reproducible example and tag my name, thanks!

**Comment by gabrielbull** [comment]
@pedrodurek You are not augmenting react, you are overriding it, this is what everyone in this thread is trying to say. The reproduction is as simple as `yarn add react-i18next` and then the project is no longer working, that's it, a simple install of `react-i18next` and typescript no longer compiles a normal react project.

**Comment by liangxiwei** [comment]
I have the same issue...why the react-i18next overwrite the module react field??

**Comment by liangxiwei** [comment]
I fork this project and remove some code which break typecheck. if any one have the same problem, see https://www.npmjs.com/package/react-i18next-fix-type-check

**Comment by adrai** [comment]
allowObjectInHTMLChildren was introduced because of this discussion: https://github.com/i18next/react-i18next/issues/1483

@LukasKalbertodt @high1 @eps1lon @enoh-barbu @rphmee-lo @ghost @ripvannwinkler @davehowson @joshkel @seemX17 @wangpin34 you participated in that discussion/issue... What do you think, what should we do with `allowObjectInHTMLChildren`?

The suggestion seems to remove it again, like: https://github.com/liangxiwei/react-i18next/commit/3cb152ab7fdbf34bb273a3e2d9c4cda48589ad03

**Comment by dieale21** [comment]
Hey guys, I had a similar issue and this article helps me.
https://bobbyhadz.com/blog/react-this-tags-children-prop-expects-single-child

**Comment by pedrodurek** [comment]
@gabrielbull, yes, I am type augmenting react, you can take a look [here](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) for more information. The only scenario where type augmentation actually overwrites types from a library is when the library augmented isn't imported into the file. [That's not the case here](https://github.com/i18next/react-i18next/blob/master/index.d.ts#L12).

If something is breaking due to the code introduced here, can someone share a reproducible example so I can investigate what it could be, please?

**Comment by sushanyadav** [comment]
For me, `PropsWithChildren` fixed the issue.

```tsx
import React, {
  type PropsWithChildren,
} from "react";

interface IconButtonProps {}

export const IconButton = ({
  children
}: PropsWithChildren<IconButtonProps>) => {
  return (
    <button>
    <div className="flex gap-4">test</div>
      {children}
       test
    </button>
  );
};
```

**Comment by serjiosilent** [comment]
Have the same issue with using MUI.

Importing TextField and get an error:

```
Type '{ label: string | undefined; placeholder: string | undefined; variant: "filled"; fullWidth: true; id: string; disabled: boolean; size: "small" | undefined; InputLabelProps: Omit<HTMLAttributes<HTMLLabelElement>, "color">; InputProps: { ...; }; inputProps: InputHTMLAttributes<...>; }' is not assignable to type 'Omit<OutlinedTextFieldProps | FilledTextFieldProps | StandardTextFieldProps, "variant">'.
  The types of 'InputLabelProps.children' are incompatible between these types.
    Type 'ReactI18NextChildren | Iterable<ReactI18NextChildren>' is not assignable to type 'ReactNode'.
      Type 'Record<string, unknown>' is not assignable to type 'ReactNode'.
        Type 'Record<string, unknown>' is missing the following properties from type 'ReactPortal': key, children, type, props
```

Any solution didn't helped

**Comment by sourdenis** [comment]
@serjiosilent I have the same issue:
I recreated it here:
https://codesandbox.io/s/i18next-type-error-mui-kfl7pd

**Comment by adrai** [comment]
@sourdenis you missed to define the namespace level here: https://codesandbox.io/s/i18next-type-error-mui-forked-p23dcd?file=/src/i18n.ts:159-173

**Comment by serjiosilent** [comment]
@adrai in my case I'm not using any translations in components, just installed `react-i18next` and after running app get this error

**Comment by adrai** [comment]
> @adrai in my case I'm not using any translations in components, just installed `react-i18next` and after running app get this error

I can't see any error in the codesandbox example.

**Comment by sourdenis** [comment]
@adrai according to this: https://www.i18next.com/overview/getting-started, my config seems legit :) "translation" <-- this is default ns ;)

**Comment by adrai** [comment]
> @adrai according to this: https://www.i18next.com/overview/getting-started, my config seems legit :) "translation" <-- this is default ns ;)

also in the getting started guide you see the translation namespace is defined in the language object:
<img width="331" alt="image" src="https://github.com/i18next/react-i18next/assets/1086194/1b502b5e-4810-4b68-9beb-e498d2071f1e">

**Comment by sourdenis** [comment]
<img width="1211" alt="Screenshot 2023-09-08 at 11 50 14" src="https://github.com/i18next/react-i18next/assets/19668462/ce96e35e-4de7-4355-b278-7bb564b6e1ce">

I see this error

**Comment by adrai** [comment]
> <img alt="Screenshot 2023-09-08 at 11 50 14" width="1211" src="https://user-images.githubusercontent.com/19668462/266556236-ce96e35e-4de7-4355-b278-7bb564b6e1ce.png">
> I see this error

This is not an i18next problem...
You might ask @mui/material because the TextField is not from react-i18next

**Comment by sourdenis** [comment]
> > @adrai according to this: https://www.i18next.com/overview/getting-started, my config seems legit :) "translation" <-- this is default ns ;)
> 
> also in the getting started guide you see the translation namespace is defined in the language object: <img alt="image" width="331" src="https://user-images.githubusercontent.com/1086194/266556118-1b502b5e-4810-4b68-9beb-e498d2071f1e.png">
> 
> but your example has no namespace: <img alt="image" width="401" src="https://user-images.githubusercontent.com/1086194/266556307-9f8aecd0-5a5b-4457-a8b5-0e9aa77d415f.png">

ok, that was my bad. Sry.
But it doesn't change the outcome

**Comment by sourdenis** [comment]
well, it works with older version of i18next / react-i18next :)

**Comment by adrai** [comment]
@nicegamer7 can you have a look at this?
maybe this can be optimized? https://github.com/i18next/react-i18next/pull/1669
https://github.com/i18next/react-i18next/commit/16312fff7ec16255b9d59a7f7bdfcb7d726e7a70

**Comment by nicegamer7** [comment]
This looks like an issue with MUI's types. I'll take a look when I get a chance.

**Comment by nicegamer7** [comment]
I found the issue in MUI's types. I'll make a PR there in a bit and post here when I do.

**Comment by nicegamer7** [comment]
You can install the version of `mui-material` from the above PR by setting the version to `https://pkg.csb.dev/mui/material-ui/commit/69a9e797/@mui/material` in your `package.json`. If anyone who was experiencing the issue could try it and report whether this fixes it, that'd be appreciated.

**Comment by nphmuller** [comment]
The error is gone with the version you linked. Haven't been able to test everything thoroughly because there are a few other breaking changes in the version that's currently on @mui/material's master branch.

Would it be too much trouble if you could explain the fix? I see you typed the children prop of `<FormControl />` as `React.HTMLAttributes<HTMLDivElement>` and the children prop from `<FormLabel />` from `React.LabelHTMLAttributes<HTMLLabelElement>['children']` instead of `React.ReactNode`. Is this component special, or would you expect other libraries to potentially do the same? If I understood correctly the "normal" typing of the children prop should be `React.ReactNode`, so I don't yet understand why this rule doesn't apply for these components.

**Comment by nicegamer7** [comment]
The argument in the `renderInput` prop is typed as containing `React.HTMLAttributes<HTMLDivElement>['children']` and `React.HTMLAttributes<HTMLLabelElement>['children']`, so if these types are augmented (as they are in this package), you'll get a type error if you try to pass these to a component expecting `React.ReactNode`.

Does that make sense? Hopefully my explanation is okay.

**Comment by nphmuller** [comment]
Ah, so there was a mismatch in their own typings. That totally makes sense. Thanks for explaining!

**Comment by developergunny** [comment]
I also had the same phenomenon as @serjioslient.

Following @Sourdenis' advice, I downgraded to react-i18next v.12.2.2 and i18next 22.5.1 and the problem went away.

**Comment by MrTim** [comment]
For those who will bump into the same issue, I'll share my experience regarding this problem.

I got same error with following dependencied (listing only important ones):
```
"devDependencies": {
  "react-scripts": "^5.0.0",
  “typescript”: “^4.6.2"
},
"dependencies": {
  "i18next": "^23.5.1",
  "react": "^18.2.0",
  "react-dom": "^18.2.0",
  "react-i18next": "^13.2.2"
}
```
Important here is a version of typescript.
After I updated to typescript v5 the error is gone. You would get another problem of legacy peer deps (because cra doesn't support latest typescript version) and that will be a trade of in using latest versions of i18next libs.

**Comment by csharpsi** [comment]
> You can install the version of `mui-material` from the above PR by setting the version to `https://pkg.csb.dev/mui/material-ui/commit/69a9e797/@mui/material` in your `package.json`. If anyone who was experiencing the issue could try it and report whether this fixes it, that'd be appreciated.

@nicegamer7 this resolved the issue for me, thanks! Hopefully your PR gets merged soon 🤞

**Comment by irangarcia** [comment]
It will get fixed?

https://github.com/i18next/react-i18next/issues/1543#issuecomment-1252135618

**Comment by vu-cv** [comment]
> > <img alt="Screenshot 2023-09-08 at 11 50 14" width="1211" src="https://user-images.githubusercontent.com/19668462/266556236-ce96e35e-4de7-4355-b278-7bb564b6e1ce.png">
> > I see this error
> 
> This is not an i18next problem... You might ask @mui/material because the TextField is not from react-i18next

Hi my friend, how to fix it

**Comment by FOSSforlife** [comment]
In my case, using MUI Autocomplete with MUI TextField, here was the solution:

Replace:
```
      renderInput={(params) => (
        <TextField {...params} />
      )}
```

with:
```
      renderInput={(params) => (
        <TextField {...(params as AutocompleteRenderInputParams & { InputLabelProps: React.PropsWithChildren<InputLabelProps> })} />
      )}
```

**Comment by vitaliihra** [comment]
I experiencing a similar to [serjiosilent](https://github.com/serjiosilent) and [sourdenis](https://github.com/sourdenis) issue 
So, I used the older react-i18next(11.18.0) version it worked, but can anyone explain why it happened?

Why did only the installation of react-i18next cause these issues with MUI's TextFields?

Thanks in advance.

**Comment by zhouru1bin** [comment]
> Have the same issue with using MUI.
> 
> Importing TextField and get an error:
> 
> ```
> Type '{ label: string | undefined; placeholder: string | undefined; variant: "filled"; fullWidth: true; id: string; disabled: boolean; size: "small" | undefined; InputLabelProps: Omit<HTMLAttributes<HTMLLabelElement>, "color">; InputProps: { ...; }; inputProps: InputHTMLAttributes<...>; }' is not assignable to type 'Omit<OutlinedTextFieldProps | FilledTextFieldProps | StandardTextFieldProps, "variant">'.
>   The types of 'InputLabelProps.children' are incompatible between these types.
>     Type 'ReactI18NextChildren | Iterable<ReactI18NextChildren>' is not assignable to type 'ReactNode'.
>       Type 'Record<string, unknown>' is not assignable to type 'ReactNode'.
>         Type 'Record<string, unknown>' is missing the following properties from type 'ReactPortal': key, children, type, props
> ```
> 
> Any solution didn't helped
> 
> UPD: application become to stable after I set `"react-i18next": "^11.18.0"`


I also encountered the same problem, have you solved it?

**Comment by vitaliihra** [comment]
@zhouru1bin you can either downgrade the react-i18next or use the pr of mui above. Also, when I updated the typescript to v5 it solved the issue for me, but I am not sure why it appeared after all

**Comment by herzaso** [comment]
any reason not to use the following syntax?
```
<Trans i18nKey='MY_KEY' values={{foo: 'bar'}}>
  Hello <b>{foo}</b>
</Trans>
```
Assuming MY_KEY = `Hello <1>{{foo}}</1>`

(instead of passing object as a child, just pass the value)

**Comment by undefinederror** [comment]
> any reason not to use the following syntax?
> 
> ```
> <Trans i18nKey='MY_KEY' values={{foo: 'bar'}}>
>   Hello <b>{foo}</b>
> </Trans>
> ```
> 
> Assuming MY_KEY = `Hello <1>{{foo}}</1>`
> 
> (instead of passing object as a child, just pass the value)

That would not work with [i18next-parser](https://github.com/i18next/i18next-parser/), which would write `MY_KEY = "Hello <1>{foo}</1>"` in your translation file. 

What seems to work for me is 
```jsx
<Trans i18nKey='MY_KEY' values={{foo: 'bar'}}>
  Hello <b>{'{'}{foo}{'}'}</b>
</Trans>
```
Which does correctly write `MY_KEY = "Hello <1>{{foo}}</1>"` in your translation file.

**Comment by minhsu12113** [comment]
I have no idea why a library top translate in web development but the simple task like that can't work properly, let's say I'm using React + TypeScript and I want to translate a paragraph like this:

Hello **Justin** this is your application

`<Trans i18nKey='MY_KEY' values={{userName: 'Justin'}}>
  Hello <b>{userName}</b>
</Trans>`

MY_KEY= Hello <0> {{userName}} </0> this is your application

And i get error **Cannot find name 'userName'**

The above text is super simple, and I got bad experimence to do that, the syntax the error about type, why that hard to complete in easy way?

**Comment by sqiggle** [comment]
Hi, I am still running into an issue when using Mui/Material UI with react-i18next. Specifically, the Alert component is giving this error. Some components also are giving an error when using the className prop. These errors only happen when I have react-i18next installed. Based on some earlier messages, I believe these errors might be on Mui's end.

**Comment by Langsdorf** [comment]
Just ran into this with shadcn components



```json
    "react-i18next": "^16.5.1",
    "i18next": "^25.7.3",
```

```ts
function SelectTrigger({
  className,
  size = "default",
  children,
  ...props
}: React.ComponentProps<typeof SelectPrimitive.Trigger> & {
  size?: "sm" | "default"
}) {
  return (
    <SelectPrimitive.Trigger
      data-slot="select-trigger"
      data-size={size}
      className={cn(
        "border-input data-[placeholder]:text-muted-foreground dark:bg-input/30 dark:hover:bg-input/50 focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive dark:aria-invalid:border-destructive/50 gap-1.5 rounded-lg border bg-transparent py-2 pr-2 pl-2.5 text-sm transition-colors select-none focus-visible:ring-[3px] aria-invalid:ring-[3px] data-[size=default]:h-8 data-[size=sm]:h-7 data-[size=sm]:rounded-[min(var(--radius-md),10px)] *:data-[slot=select-value]:flex *:data-[slot=select-value]:gap-1.5 [&_svg:not([class*='size-'])]:size-4 flex w-fit items-center justify-between whitespace-nowrap outline-none disabled:cursor-not-allowed disabled:opacity-50 *:data-[slot=select-value]:line-clamp-1 *:data-[slot=select-value]:flex *:data-[slot=select-value]:items-center [&_svg]:pointer-events-none [&_svg]:shrink-0",
        className
      )}
      {...props}
    >
      {children}
      <SelectPrimitive.Icon asChild>
        <ChevronDownIcon className="text-muted-foreground size-4 pointer-events-none" />
      </SelectPrimitive.Icon>
    </SelectPrimitive.Trigger>
  )
}


Type 'ReactI18NextChildren | Iterable<ReactI18NextChildren>' is not assignable to type 'string | number | bigint | boolean | ReactElement<unknown, string | JSXElementConstructor<any>> | Iterable<ReactNode> | ... 4 more ... | undefined'.
  Type 'Iterable<ReactI18NextChildren>' is not assignable to type 'string | number | bigint | boolean | ReactElement<unknown, string | JSXElementConstructor<any>> | Iterable<ReactNode> | ... 4 more ... | undefined'.
    Type 'Iterable<ReactI18NextChildren>' is not assignable to type 'Iterable<ReactNode>'.
      The types returned by '[Symbol.iterator]().next(...)' are incompatible between these types.
        Type 'IteratorResult<ReactI18NextChildren, any>' is not assignable to type 'IteratorResult<ReactNode, any>'.
          Type 'IteratorYieldResult<ReactI18NextChildren>' is not assignable to type 'IteratorResult<ReactNode, any>'.
            Type 'IteratorYieldResult<ReactI18NextChildren>' is not assignable to type 'IteratorYieldResult<ReactNode>'.
              Type 'ReactI18NextChildren' is not assignable to type 'ReactNode'.
                Type 'Record<string, unknown>' is not assignable to type 'ReactNode'.
                  Type 'Record<string, unknown>' is missing the following properties from type 'ReactPortal': children, type, props, keyts(2322)
```

The solution was to wrap with React.PropsWithChildren<>

```ts
function SelectTrigger({
    className,
    size = "default",
    children,
    ...props
}: React.PropsWithChildren<React.ComponentProps<typeof SelectPrimitive.Trigger>> & {
    size?: "sm" | "default"
}) { .... }
```
