### ISSUE TITLE
Linting of TFunction fails since the last update

### ISSUE THREAD

**Issue by mxsxs2** [i18next/react-i18next#1212]
## 💥 Regression Report

Linting of `TFunction` fails since the last update. The `t` function should accept its `key` parameter to be `string | string []`. However, it seems to expect to be `never`.

`K` seems to resolve to `never` at https://github.com/i18next/react-i18next/blob/a4aaf65e937e2b5ef021be41d581614a9aa80c73/src/ts4.1/index.d.ts#L91

## Last working version

Worked up to version: 11.7.4

Stopped working in version: 11.8.0

## To Reproduce

```js
import React from 'react'
import { useTranslation } from 'react-i18next/*'

const MyComponent= ()=>{
    const {t} = useTranslation()
    return <span>{t('hello')}</span>
}

export default MyComponent
```

## Expected behavior

I expect to not have _Argument of type 'string' is not assignable to parameter of type 'never'.ts(2769)_ at line 6 for `t('hello')`

Full error:

>  error TS2769: No overload matches this call.
  Overload 1 of 2, '(key: never, options?: string | TOptions<StringMap> | undefined): never', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'never'.
  Overload 2 of 2, '(key: never, defaultValue?: string | undefined, options?: string | TOptions<StringMap> | undefined): never', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'never'.
## Your Environment

- *runtime version*: node 14.15.1
- *i18next version*: 11.8.0
- *TypeScript version*: 4.1.2
- *os*: Windows with Ubuntu WSL2

**Comment by paulrostorp** [comment]
same here:
![Screenshot 2020-12-07 at 14 52 58](https://user-images.githubusercontent.com/1866649/101362774-d5ee0200-38a0-11eb-9880-5dd25238f4b6.png)

**Comment by adrai** [comment]
@pedrodurek can you have a look at this?

**Comment by JeroenReumkens** [comment]
Same here, was looking into failing builds for the past 30 mins. This only seems to be the case in the 4.1 typings, 4.0.x is fine. At least it helped me find out our CI users a different TS version compared to my local environment 😅

**Comment by pedrodurek** [comment]
sure

**Comment by goldmont** [comment]
Same here.

**Comment by pedrodurek** [comment]
Hey guys, I'm still investigating it, but I managed to simulate the error using CRA. When I performed the tests for the first time, CRA wasn't supporting typescript 4.1 properly, so I used pure webpack (https://github.com/pedrodurek/i18n-type-tests), which works perfectly. 

I'll let you guys know as soon as I sort that out.

@adrai in the meantime, what do you suggest?
1 - I can create a PR disabling TS 4.1, which will fallback to the old type definitions.
2 - We can rollback the changes.
3 - Just wait until I find out the reason.

**Comment by adrai** [comment]
I'm not a TS user...
others have to say 🤷‍♂️
in the meantime option 3 😉

**Comment by tigerabrodi** [comment]
If any help is needed, you know where to find me :tiger2: :tada: :smiley:

**Comment by JeroenReumkens** [comment]
@pedrodurek  I'm using NextJS. They do support TS 4.1.
As an answer to your other question; Why is a separate typing needed for TS 4.1? I've actually never seen a library do this. So would there be a downside to using the default types? I tried to take a look as the 4.1 typings to spot any meaningful differences, but I found them a lot harder to decipher 😅

**Comment by JeroenReumkens** [comment]
Oh! I took a look at [your example](https://github.com/pedrodurek/i18n-type-tests/blob/master/src/components/MultipleNamespaces/index.tsx) and noticed that the error does NOT occur when you pass a namespace to `useTranslation`. My implementation currently does not pass a namespace, which results in the error.

**Comment by pedrodurek** [comment]
Hey guys, I managed to fix the issue. I'm gonna add two examples (with and without namespaces) under `examples` folder and open a PR.

**Comment by pedrodurek** [comment]
It should be fixed now

**Comment by vtrphan** [comment]
Hi, i'm still getting this error
`No overload matches this call.
  Overload 1 of 2, '(key: Normalize<{ formattedDate: string; app: { title: string; }; loginPage: { titleUnauthenticated: string; titleAuthenticated: string; subheaderUnauthenticated: string; subheaderAuthenticated: string; ... 6 more ...; forgotPwdBtnLabel: string; }; homePage: { ...; }; nmvsUserPage: { ...; }; }>, options?: string | ... 1 more ... | undefined): string | ... 15 more ... | { ...; }', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'Normalize<{ formattedDate: string; app: { title: string; }; loginPage: { titleUnauthenticated: string; titleAuthenticated: string; subheaderUnauthenticated: string; subheaderAuthenticated: string; ... 6 more ...; forgotPwdBtnLabel: string; }; homePage: { ...; }; nmvsUserPage: { ...; }; }>'.
  Overload 2 of 2, '(key: Normalize<{ formattedDate: string; app: { title: string; }; loginPage: { titleUnauthenticated: string; titleAuthenticated: string; subheaderUnauthenticated: string; subheaderAuthenticated: string; ... 6 more ...; forgotPwdBtnLabel: string; }; homePage: { ...; }; nmvsUserPage: { ...; }; }>, defaultValue?: string | undefined, options?: string | ... 1 more ... | undefined): string | ... 15 more ... | { ...; }', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'Normalize<{ formattedDate: string; app: { title: string; }; loginPage: { titleUnauthenticated: string; titleAuthenticated: string; subheaderUnauthenticated: string; subheaderAuthenticated: string; ... 6 more ...; forgotPwdBtnLabel: string; }; homePage: { ...; }; nmvsUserPage: { ...; }; }>'.  TS2769

    55 |                        <ListItemIcon>{importanceIcon(sortingPriority)}</ListItemIcon>
    56 |                        <ListItemText
  > 57 |                                primary={t(translations.homePage.newsItem.primary, {`

Please advise

**Comment by pedrodurek** [comment]
Hey @vtrphan, since it's not related to this issue, I'd advice you to open another one and provide more info. But in a nutshell, I can see that you're passing an object as key to the `t` function instead of a `string`.

**Comment by vtrphan** [comment]
@pedrodurek Yes i'm using the approach/setup from react-boilerplate
https://github.com/react-boilerplate/react-boilerplate-cra-template
to make use of Intellisense (passing in an object instead of a string). 
This used to work with react-i18next v11.7 and below, only report error in 11.8 and up

**Comment by pedrodurek** [comment]
That's weird because even in the v11.7, it was only accepting `string` or `TemplateStringsArray` as key. Have you checked one of the examples here? We're using the last CRA version.
https://github.com/i18next/react-i18next/tree/master/example/react-typescript4.1https://github.com/i18next/react-i18next/tree/master/example/react-typescript4.1

**Comment by adrianolsk** [comment]
@vtrphan I may be wrong, but looks like you are not using the i18n doing this `t(translations.homePage.newsItem.primary`, I think it's probably using the value from your object because it is not finding your key and using it as a fallback.
In my understanding you should be using like this `t('homePage.newsItem.primary')`

**Comment by vtrphan** [comment]
@adrianolsk Hi, it is this approach/setup that i'm following: 
https://cansahin.gitbook.io/react-boilerplate-cra-template/building-blocks/i18n
They're converting the translation json into object to take advantage of the intellisense feature

**Comment by mxsxs2** [comment]
> Hey guys, I managed to fix the issue. I'm gonna add two examples (with and without namespaces) under `examples` folder and open a PR.

The PR fixed my issue. Thanks!

**Comment by joelpoloney** [comment]
Has anyone run into the situation where you're swapping out the "base" of a key? This used to work but now requires extra TypeScript casting:

Before:
```ts
const i18nBase = isSubmitted ? 'path.to.something.resubmit' : 'path.to.something.submit'
const title = t(`${i18nBase}.title`)
```

Interpreting the string in this manor fails to compile with errors like `No overload matches this call.`. I can fix this by casting to a const with:
```ts
const i18nBase = isSubmitted ? 'path.to.something.resubmit' : 'path.to.something.submit'
const title = t(`${i18nBase}.title` as const)
```

but it feels like something that I shouldn't have to do. Is there a better way to do this? We exercise this pattern quite frequently in our codebase, especially for re-usable components which might be in different states and I was hoping to avoid having to rewrite them all.

Thanks!

**Comment by pedrodurek** [comment]
Hey @joelpoloney, I believe I answered your question here: https://github.com/i18next/react-i18next/pull/1193#issuecomment-752283441
